package com.example.wazitoecommerce.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val SPLASH_URL = "splash_screen"
const val CHAIRS_URL = "chairs_screen"
const val TABLES_URL = "tables_screen"
const val SOFA_URL = "sofa_screen"
const val CONTROL_URL = "control_screen"
const val ELECTRONICS_URL = "electronics_screen"
const val UTENSILS_URL = "utensils_screen"
const val BEDS_URL = "beds_screen"
const val CARS_URL = "cars_screen"
